userInput = input("Enter some test:\n")
outputStr = userInput.replace("a","4")
outputStr = outputStr.replace("b","8")
outputStr = outputStr.replace("e","3")
outputStr = outputStr.replace("l","1")
outputStr = outputStr.replace("o","0")
outputStr = outputStr.replace("s","5")
outputStr = outputStr.replace("t","7")

print(outputStr)
